#!/bin/bash
# Claude Relay Service 一键发布脚本
# 用法: ./release.sh [--yes] [版本号]
# 示例: ./release.sh 1.1.260
#       ./release.sh          # 自动递增 patch 版本
#       ./release.sh --yes    # 跳过所有确认

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Git 远程仓库名（自动检测，优先 origin，其次 gitcode）
if git remote | grep -q "^origin$"; then
    GIT_REMOTE="origin"
elif git remote | grep -q "^gitcode$"; then
    GIT_REMOTE="gitcode"
else
    GIT_REMOTE=$(git remote | head -1)
fi

# 解析参数
SKIP_CONFIRM=false
VERSION_ARG=""

for arg in "$@"; do
    case $arg in
        --yes|-y)
            SKIP_CONFIRM=true
            ;;
        *)
            VERSION_ARG="$arg"
            ;;
    esac
done

echo -e "${BLUE}🚀 Claude Relay Service 发布脚本${NC}"
echo ""

# 检查是否在项目根目录
if [ ! -f "VERSION" ] || [ ! -f "package.json" ]; then
    echo -e "${RED}❌ 请在项目根目录运行此脚本${NC}"
    exit 1
fi

# 检查是否有未提交的更改
if [ -n "$(git status --porcelain)" ]; then
    echo -e "${YELLOW}⚠️  检测到未提交的更改：${NC}"
    git status --short
    echo ""
    if [ "$SKIP_CONFIRM" = false ]; then
        read -p "是否继续发布？(y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo -e "${YELLOW}已取消${NC}"
            exit 0
        fi
    else
        echo -e "${YELLOW}跳过确认 (--yes)${NC}"
    fi
fi

# 获取当前版本
CURRENT_VERSION=$(cat VERSION | tr -d '[:space:]')
echo -e "当前版本: ${BLUE}${CURRENT_VERSION}${NC}"

# 计算新版本
if [ -n "$VERSION_ARG" ]; then
    NEW_VERSION="$VERSION_ARG"
else
    # 自动递增 patch 版本
    MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
    MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
    PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
    NEW_PATCH=$((PATCH + 1))
    NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
fi

NEW_TAG="v${NEW_VERSION}"
echo -e "新版本:   ${GREEN}${NEW_VERSION}${NC}"
echo ""

if [ "$SKIP_CONFIRM" = false ]; then
    read -p "确认发布 ${NEW_VERSION}？(y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${YELLOW}已取消${NC}"
        exit 0
    fi
fi

echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

# Step 1: 构建前端
echo -e "${BLUE}[1/6] 构建前端...${NC}"
cd web/admin-spa
npm ci --silent
npm run build
cd ../..
echo -e "${GREEN}✅ 前端构建完成${NC}"

# Step 2: 更新 VERSION 文件
echo -e "${BLUE}[2/6] 更新版本号...${NC}"
echo "$NEW_VERSION" > VERSION
echo -e "${GREEN}✅ VERSION 已更新为 ${NEW_VERSION}${NC}"

# Step 3: 推送 web-dist 分支
echo -e "${BLUE}[3/6] 推送前端产物到 web-dist 分支...${NC}"

# 保存当前分支
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# 使用 worktree 方式处理，避免影响当前工作区
TEMP_WORKTREE=$(mktemp -d)
REPO_URL=$(git remote get-url ${GIT_REMOTE})

# 克隆一个干净的仓库到临时目录
git clone --depth 1 --single-branch "$REPO_URL" "$TEMP_WORKTREE" 2>/dev/null || {
    # 如果 clone 失败，使用本地目录
    cd "$TEMP_WORKTREE"
    git init
    git remote add origin "$REPO_URL"
}

cd "$TEMP_WORKTREE"

# 检查并切换到 web-dist 分支
if git ls-remote --heads origin web-dist | grep -q web-dist; then
    git fetch origin web-dist
    git checkout -b web-dist origin/web-dist || git checkout --orphan web-dist
else
    git checkout --orphan web-dist
fi

# 清空并复制前端产物
git rm -rf . 2>/dev/null || true
rm -rf * 2>/dev/null || true
cp -r "${OLDPWD}/web/admin-spa/dist"/* .

# 添加 README
cat > README.md << EOF
# Claude Relay Service - Web Frontend Build

This branch contains the pre-built frontend assets for Claude Relay Service.

**DO NOT EDIT FILES IN THIS BRANCH DIRECTLY**

These files are automatically generated by the release script.

Version: ${NEW_VERSION}
Build Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
EOF

# 提交并推送
git add --all
git commit -m "chore: update frontend build for ${NEW_TAG} [skip ci]" || echo "无变更"
git push origin web-dist --force

# 返回原目录
cd "${OLDPWD}"

# 清理临时目录
rm -rf "$TEMP_WORKTREE"

echo -e "${GREEN}✅ web-dist 分支已更新${NC}"

# Step 4: 创建并推送 Tag
echo -e "${BLUE}[4/5] 创建 Git Tag...${NC}"
git tag -a "${NEW_TAG}" -m "Release ${NEW_TAG}" 2>/dev/null || echo "Tag 已存在"
git push ${GIT_REMOTE} "${NEW_TAG}" 2>/dev/null || echo "Tag 已推送"
echo -e "${GREEN}✅ Tag ${NEW_TAG} 已创建${NC}"

# Step 5: 提交主分支
echo -e "${BLUE}[5/5] 提交主分支更改...${NC}"
git add VERSION release.sh 2>/dev/null || true
git commit -m "chore: bump version to ${NEW_VERSION} [skip ci]" || echo "无变更"
git push ${GIT_REMOTE} "$CURRENT_BRANCH"
echo -e "${GREEN}✅ 主分支已推送${NC}"

echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}🎉 发布完成！${NC}"
echo ""
echo -e "版本:  ${GREEN}${NEW_VERSION}${NC}"
echo -e "Tag:   ${GREEN}${NEW_TAG}${NC}"
echo ""
echo -e "用户更新方式:"
echo -e "  ${BLUE}crs update${NC}"
